### ISSUE TITLE
Do you need two separate DSNs any more?

### ISSUE THREAD

**Issue by evaryont** [Findus23/plugin-SentryLogger#1]
I believe with the latest versions of the Sentry SDKs, the private key does not need to be included in the server-side DSN. Because of that, the PHP and JavaScript/browser DSNs are identical in my use.

It would be simpler in the UI if javascript support was a simple checkbox to enable browser errors being logged, rather than the possible confusion of looking for a special DSN that doesn't exist any more.

And, if this is all correct, I think it would be best if Javascript error capturing was enabled by default.

**Comment by Findus23** [comment]
Hi,

You are right, the two DSN don't need to be different. The main reason why I made two settings, is that I am tracking it into two separate projects (which seems a bit unnecessary to be fair).

And I really disagree that Javascript tracking should be enabled by default. While this plugin really helps me report bugs and find issues in newer PHP versions, I don't think anyone should use it without being exactly aware of what it does (and what privacy implications it has), so keeping it non-user-friendly is kind of intentional. :slightly_smiling_face:
